- name: installing pthon
  pre_tasks:
    - name: python plsss
    ansible.builtin.debug:
      msg: "NOW"

- name: Choosing Ubuntu
  ansible.builtin.import_tasks:
    file: ubuntu.yml
  when: (ansible_facts['distribution'] == 'Ubuntu')
  tags: [ MySQL ]

- name: Choosing Amazon
  ansible.builtin.import_tasks:
    file: amazon.yml
  when: (ansible_facts['distribution'] == 'Amazon')
  tags: [ MySQL ]