- name: Include vars
  ansible.builtin.include_vars:
    file: vars/default.yml
    name: variables
  tags: [ Wordpress ]

- name: Extract wordpress arch
  ansible.builtin.unarchive:
    src: http://wordpress.org/latest.tar.gz
    dest: /usr/share/nginx/html/
    remote_src: true
    owner: nginx
    group: nginx
    extra_opts: [--strip-components=1]
  tags: [ Wordpress ]

- name: Create a directory for wordpress
  ansible.builtin.file:
    path: /usr/share/nginx/html/wp-content/uploads
    state: directory
    recurse: true
    owner: nginx
    group: nginx
    mode: 0644
  tags: [ Wordpress ]

- name: Copy file to host
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: /usr/share/nginx/html/wp-config.php
  tags: [ Wordpress ]

- name: Download WP cli
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /tmp/
  tags: [ Wordpress ]

- name: Renaming and changing rights
  ansible.builtin.copy:
    src: /tmp/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: u+rx,g-rx,o-rwx
    owner: nginx
    group: nginx
    remote_src: true
  tags: [ Wordpress ]

- name: WP core installation
  ansible.builtin.command: "sudo -u nginx /usr/local/bin/wp core install --url={{ variables.wp_url }} --title={{ variables.wp_title }} --admin_name={{ variables.wp_admin }} --admin_password={{ variables.wp_password }} --admin_email={{ variables.wp_email }}"
  args:
    chdir: "/usr/share/nginx/html/"
  tags: [ Wordpress ]

- name: Install WP plugins
  command: "sudo -u nginx /usr/local/bin/wp plugin install {{ item }} --activate"
  loop: [ calculated-fields-form ]
  args:
    chdir: "/usr/share/nginx/html/"
  tags: [ Wordpress ]

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  tags: [ System, Wordpress ]

- name: Include handlers
  ansible.builtin.include_tasks:
    file: roles/wordpress/handlers/main.yml
  tags: [ System, Wordpress ]