# while installing wordpress 2x --alow-root --> DANGEROUS/SHOULD BE CHANGED OR FIXED
# "sudo -u vagrant -i -- wp config create --dbname={{mysql_db}} --dbuser={{mysql_user}} --dbpass='{{mysql_password}}' --dbhost=localhost --dbprefix={{mysql_db_prefix}} --config-file=/var/www/html/wp-config.php --path='/var/www/html'"

- name: Check if already installed --> /var/www/html/wp-config.php
  stat:
    path: /var/www/html/wp-config.php
  register: wp_config_stat

- name: Stats of /var/www/html/wp-config.php
  ansible.builtin.debug:
    var: wp_config_stat

- name: Create wordpress DB
  community.mysql.mysql_db: 
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /run/mysqld/mysqld.sock
  when: "wp_config_stat.stat.exists == false"

- name: Add user with DB privileges 
  community.mysql.mysql_user:
    name: '{{ mysql_user }}'
    password: '{{ mysql_password }}'
    priv: '*.*:ALL'
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  when: "wp_config_stat.stat.exists == false"

- name: Delete /var/www/html
  ansible.builtin.file:
    path: /var/www/html
    state: absent
  when: "wp_config_stat.stat.exists == false"

- name: Create /var/www/html
  ansible.builtin.file:
    path: /var/www/html
    recurse: true
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  when: "wp_config_stat.stat.exists == false"

- name: Extract wordpress.tgz into /var/www/html
  ansible.builtin.unarchive:
    src:  https://wordpress.org/latest.tar.gz
    dest: /var/www/html
    remote_src: yes
    owner: www-data
    group: www-data
    extra_opts: [--strip-components=1]
  when: "wp_config_stat.stat.exists == false"

- name: Check if already installed --> /usr/local/bin/wp
  stat:
    path: /usr/local/bin/wp
  register: wp_cli_stat

- name: Install the wp-cli
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    owner: www-data
    group: www-data
    mode: '0755'
  when: "wp_cli_stat.stat.exists == false"

- name: Create wp-config.php
  args: 
    chdir: /var/www/html
  ansible.builtin.shell: "wp config create --dbname={{mysql_db}} --dbuser={{mysql_user}} --dbpass='{{mysql_password}}' --dbhost=localhost --dbprefix={{mysql_db_prefix}} --config-file=/var/www/html/wp-config.php --path='/var/www/html' --allow-root"
  when: "wp_config_stat.stat.exists == false"

- name: Install Wordpress
  ansible.builtin.shell: "sudo -u www-data wp core install --url={{wp_url1}} --title={{wp_title1}} --admin_user={{wp_admin}} --admin_password={{wp_password}} --admin_email={{wp_email}}"
  args: 
    chdir: "/var/www/html"
  when: "wp_config_stat.stat.exists == false"
  
- name: Change privilages for the wp-config.php file
  ansible.builtin.file:
    path: /var/www/html/wp-config.php
    owner: www-data
    group: www-data
    mode: '600'

  
